### ISSUE TITLE
Not enough Lorem Ipsum (this is just a joke)

### ISSUE THREAD

**Issue by marekkulesza** [the-new-developers/tnd-website#124]
## Expected Behavior

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut lobortis sapien. Pellentesque sapien eros, condimentum malesuada mi id, porta hendrerit nisi.

## Steps to Reproduce

1. Lorem ipsum
2. Lorem ipsum
3. Lorem ipsum
4. Lorem ipsum

**Comment by rodneybarnes** [comment]
Haha thanks
